# Generated by Django 4.1.4 on 2023-01-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_status_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
